### ISSUE TITLE
Fedora packaging

### ISSUE THREAD

**Issue by elliotclee** [pingswept/pysolar#112]
Attached is a .spec file to package up pysolar 0.8 for Fedora (and probably RHEL too). It builds for me on Fedora Core 30. Not sure how to proceed as far as getting it available in Fedora COPR or similar, but it might be nice to at least include it in the source tree.

[python-pysolar.spec.gz](https://github.com/pingswept/pysolar/files/3617899/python-pysolar.spec.gz)

**Comment by pingswept** [comment]
Thanks! Just added your file to the tree.
