### ISSUE TITLE
HTTPS website

### ISSUE THREAD

**Issue by jayvdb** [pingswept/pysolar#118]
Hi, I noticed that https://pysolar.org/ shows "Warning: Potential Security Risk Ahead" in Firefox because it has a wrong certificate for that domain.

https://help.github.com/en/github/working-with-github-pages/securing-your-github-pages-site-with-https may be of help to resolve this.

**Comment by pingswept** [comment]
After some mucking around with DNS, this is fixed. Thanks for pointing it out.
