### ISSUE TITLE
south of the equator

### ISSUE THREAD

**Issue by shannond100** [pingswept/pysolar#122]
I am trying to use pysolar in the southern hemisphere, but I cannot find any documentation about how to set up for the southern region of the globe.  I have tried using a negative latitude but I get inverse results.  Any help would be appreciated.
Cheers,
Shannon

**Comment by pingswept** [comment]
I believe using negative latitude should be all that is required. The frame of reference of the output is still the same, regardless of your location, so maybe you just need to multiply the results by -1 to make it sensible in your local reference frame?

**Comment by shannond100** [comment]
ok thanks,  I'll give it a go and let you know results

**Comment by shannond100** [comment]
I got this to work now, thank you for your help.  I found that this site worked well as a reference point for anyone else trying to work it out and get their head around it... https://www.suncalc.org/

I had to do a bit of massaging of the results to get it to suit my situation but the trusty nested for loop helped out with that ;).  It works perfectly now.

Cheers
