### ISSUE TITLE
Please add leap seconds after 2018

### ISSUE THREAD

**Issue by gvdkooij** [pingswept/pysolar#128]
Can you please add the leap seconds?

Full message is:
Warning (from warnings module):
  File solartime.py", line 108
    warnings.warn \
UserWarning: I don't know about leap seconds after 2018

**Comment by w00kie** [comment]
If you look at the `solartime.py` file in the repository, the code is already there, it just has not been released to Pypi yet.

**Comment by gvdkooij** [comment]
Thank you very much for helping a noob like me. It worked!




Op ma 18 mei 2020 om 02:40 schreef François Rejeté <notifications@github.com

**Comment by pingswept** [comment]
Now available in release 0.9.
