### ISSUE TITLE
Release current code to PyPI

### ISSUE THREAD

**Issue by mborsetti** [pingswept/pysolar#131]
Would be nice to have the code without the `pytz` requirement (#130 ) and without the ` I don't know about leap seconds after 2018` (#119 ) UserWarning available through `pip`!

**Comment by pingswept** [comment]
Reasonable request; will try to do that soon. Feel free to post a reminder if I don't get around to it in a week or two.

**Comment by mborsetti** [comment]
I am feeling very free to post a reminder ;)

Thanks for everything.

**Comment by pingswept** [comment]
Reminder appreciated. It’s in my queue, and nearing the top. (Okay, let’s be honest, I only sort of have a queue, it’s more like a vague cloud of responsibilities raining down on me at random, but I’m getting there.)

**Comment by pingswept** [comment]
Quick question @mborsetti: pytz can be removed from requirements.txt and python3-pysolar.spec, right? Yesterday, I tried running test_solar.py, but was prompted to install pytz, which strikes me as wrong. I suspect requirements.txt was at fault.

**Comment by mborsetti** [comment]
@pingswept sorry, the re-reapplication of the patch for some reason (i.e. my bad PR) missed reapplying the update to solar.py, which still had a dependency.  And yes, I hadn't updated any of the build files.

I am submitting the cleanup as PR #132 ; all 82 tests are running fine without `pytz` installed.

**Comment by mborsetti** [comment]
The working PR is #134

**Comment by pingswept** [comment]
Okay, 0.9 is on PyPI! Let me know if there are any weird problems. Thanks for bugging me (really!).
