### ISSUE TITLE
conda-forge update

### ISSUE THREAD

**Issue by kenkehoe** [pingswept/pysolar#138]
Thanks for the recent updates to 0.9. Is it possible to make 0.9 available on conda-forge for conda install? Currently only up to 0.8 are available with a "conda search -c conda-forge pysolar".

**Comment by pingswept** [comment]
Hi Ken! That sounds like a good idea. I hadn’t heard of conda-forge before today, but it looks like a bot has already submitted a pull request there to make the update happen: https://github.com/conda-forge/pysolar-feedstock/pull/12
I’m not sure what needs to happen to make conda-forge accept the request. Maybe the answer lies here: https://conda-forge.org/docs/maintainer/updating_pkgs.html#

Best of luck to you!

**Comment by AdamTheisen** [comment]
@pingswept Hello!  It looks like @robintw has been working on the pysolar feedstock so maybe that's who could help out with the update?  https://github.com/conda-forge/pysolar-feedstock/blob/master/recipe/meta.yaml

**Comment by robintw** [comment]
Hi @AdamTheisen and @kenkehoe - I have done things with the feedstock before, but haven't used it for a while. I've just looked at the auto-generated PR and merged it, as it all looks ok. Hopefully the packages should build soon.

**Comment by AdamTheisen** [comment]
Thanks @robintw !!

**Comment by pingswept** [comment]
From https://anaconda.org/conda-forge/pysolar, it looks like Pysolar 0.9 is now available. Please re-open this issue if I’m wrong.
