### ISSUE TITLE
Leap Seconds 2021

### ISSUE THREAD

**Issue by levydanqc** [pingswept/pysolar#139]
Hi, is it possible to add the leap seconds for 2021 please ?

**Message** : UserWarning: I don't know about leap seconds after 2020
warnings.warn \

Thank you very much !

**Comment by pingswept** [comment]
A patch that adds the 2021 value is welcome.

**Comment by levydanqc** [comment]
I added it myself, you can add (0,0) at the end of the file.

**Comment by pingswept** [comment]
Fixed in PR #140. Thanks, all.

**Comment by pingswept** [comment]
Yes, I'll try to make a release in the next few days. Feel free to post a reminder if I fail to do so.

**Comment by pingswept** [comment]
Hey, new release is up on PyPI. Please alert me here if anything is amiss. The tests and validation suite all pass, and the wheel installed successfully for me from PyPI, but there could always be subtle problems.

**Comment by MBARIMike** [comment]
It's 2023 and I'm getting this warning:
```
pysolar/solartime.py:111: UserWarning: I don't know about leap seconds after 2021
```
Thanks for maintaining this package!

**Comment by joffreypeters** [comment]
How difficult would it be to use this package as a dependency to perhaps make keeping up with leap seconds easier? 

https://pypi.org/project/leapseconddata/

**Comment by pingswept** [comment]
I guess the good news is that leap seconds will be gone in 12 years or less: https://www.nature.com/articles/d41586-022-03783-5

I think I’d rather update a text file 12 or fewer times than add another dependency.

**Comment by joffreypeters** [comment]
Excellent! I hadn't seen that bit of news!

**Comment by dietervansteenwegen** [comment]
Wanted to open a pull request with added info for june 30, 2023 (no leap seconds according to [the page you reference](https://en.wikipedia.org/wiki/Leap_second)), but there is no info for December 31st yet.

I don't really see a clean way of adding the now-known information yet, unless I can set it to (0, 0) or (0, None)...

**Comment by pingswept** [comment]
I just put in (0,0) as a placeholder until the Dec 31 value is announced in July. This data will be in the next release.
