### ISSUE TITLE
GetAltitude returns anomalous  values

### ISSUE THREAD

**Issue by stephanwaz** [pingswept/pysolar#14]
Version 0.5
Pysolar.GetAltitude(37.43,-122.17,datetime.datetime(2014,3,5,2,27)) returns 20.821778655816612 but should return a value ~ -5.  Seems like a general problem with sun angles just below the horizon (In all other cases encountered GetAltitude still returned a negative number, albeit with alot of noise.  Problematic for finding sunrise and sunset times.  Curiously Pysolar.GetAltitude(37.43,-122.171,datetime.datetime(2014,3,5,2,27)) and Pysolar.GetAltitude(37.43,-122.169,datetime.datetime(2014,3,5,2,27)) return expected values.

**Comment by solarjoe** [comment]
I guess anadrome is correct with what he suspects, the problem might be get_refraction_correction.
I had a look in the original C-code that pysolar is based on (spa.c here: http://www.nrel.gov/midc/spa/) and they added an if condition if the sun is close to the horizon:

```c
double atmospheric_refraction_correction(double pressure, double temperature,
                                         double atmos_refract, double e0)
{
    double del_e = 0;

    if (e0 >= -1*(SUN_RADIUS + atmos_refract))
        del_e = (pressure / 1010.0) * (283.0 / (273.0 + temperature)) *
                 1.02 / (60.0 * tan(deg2rad(e0 + 10.3/(e0 + 5.11))));

    return del_e;
}
```

The C source code mentiones:

```c
double atmos_refract;// Atmospheric refraction at sunrise and sunset (0.5667 deg is typical)
                         // valid range: -5   to   5 degrees, error code: 16
#define SUN_RADIUS 0.26667#
```
I will try to assemble a patch.

**Comment by solarjoe** [comment]
Ok, I commited the patch and added a pull request.
Could some of you please verify the results of the old and new version as I do not have a current pysolar project running?

**Comment by pingswept** [comment]
@solarjoe submitted a patch and it has been pulled into the master branch here: https://github.com/pingswept/pysolar/pull/23
