### ISSUE TITLE
`get_azimuth_fast`: Issue with get_azimuth_fast in near equatorial countries

### ISSUE THREAD

**Issue by pjayathissa** [pingswept/pysolar#143]
I was cross-referencing a basic radiation equation to your source code and was getting issues in near-equatorial countries (singapore), which I think is related to this logic. I was wondering what the reason for this boolean logic is?

Below is a graph of azimuth hourly profiles during the year, which I found to look a little strange. x axis is the hour of a year, and the y axis is the angle. 

<img width="936" alt="Screen Shot 2021-03-21 at 15 45 18" src="https://user-images.githubusercontent.com/6052911/111892082-e0ea2e00-8a5c-11eb-83eb-736a4b48d44a.png">

Zoomed into the the middle months:

<img width="608" alt="Screen Shot 2021-03-21 at 16 02 14" src="https://user-images.githubusercontent.com/6052911/111892282-d29d1180-8a5e-11eb-8629-6e08d82141c5.png">

https://github.com/pingswept/pysolar/blob/177b283eb8ed588d1241ecd1885d260b567d8da6/pysolar/solar.py#L175-L178

Code to regenerate the plots

```python
import pysolar
import datetime
import pytz
import matplotlib.pyplot as plt


# The size of each step in days
hour_delta = datetime.timedelta(hours=1)

start_date = datetime.datetime(2007, 1, 1, 0, 0, 0, 0)
end_date = start_date + 8760*hour_delta

Azimuths = []

for ii in range(8760):
	hour = (start_date + ii*hour_delta).replace(tzinfo = pytz.timezone("Asia/Singapore"))
	azimuth = pysolar.solar.get_azimuth_fast(1.37,1.112828,hour)
	Azimuths.append(azimuth)

plt.scatter(range(8760),Azimuths)
plt.show()
```

**Comment by pjayathissa** [comment]
I don't have sufficient experience in equatorial countries to know if this is a normal pattern.

**Comment by pingswept** [comment]
I haven't looked at this really closely, but I'm not sure that it's wrong. Your second chart looks like a sine wave centered around 0, but the negative parts are wrapped around to the top. Maybe you just need to subtract 360 degrees from the values above 180 to make it look sensibly continuous?

It would also be interesting to know if get_azimuth() returns the same values as get_azimuth_fast() for the values you're testing.

**Comment by pingswept** [comment]
Closing this for now. Please reopen if I’m in error here.
