### ISSUE TITLE
get_azimuth returns erroneous values?

### ISSUE THREAD

**Issue by alexfritz** [pingswept/pysolar#24]
Version 0.6
pysolar.solar.get_azimuth(48.248282,16.356357,datetime.datetime(2015,2,6,9,0,0,0))
returns  -326.96819097903847
which seems quite odd.

**Comment by alexfritz** [comment]
I think (but haven't had the time to confirm it) that the problem could be related to the get_topocentric_azimuth_angle function - its return statement in line 329 is missing brackets?

**Comment by polyideas** [comment]
I'm seeing negative values in my calculations for Azimuth as well.

**Comment by fetemats** [comment]
I also ran into this bug. I made a workaround so that the response matches this online calculator: http://www.solartopo.com/solar-orbit.htm

Here is my example code:
from pysolar import solar
import datetime

longitude = 12.5350953
latitude = 59.6365662
elevation = 55 #meter?

when = datetime.datetime.now()

altitude_deg = solar.get_altitude(latitude, longitude, when)

sun = solar.get_azimuth(latitude, longitude, when, elevation)
if abs(sun) >= 180:
	sundirection = abs(sun)-180 #Works before noon
else:
	sundirection = abs(sun) + 180 #Works after noon

print('angle', altitude_deg)
print('bearing', sundirection)

**Comment by jandechent** [comment]
Same for me. The function returns -317.7
What can I do?

```
from pysolar.solar import *
import datetime
from pytz import timezone
gps_l=49.4
gps_b= 8.6
dt = datetime.datetime(2017, 3, 5, 10, 0, 0, 0)
dt = dt.replace(tzinfo=timezone('Europe/Berlin'))
azi_sun=get_azimuth (gps_l, gps_b, dt)
print(azi_sun)
```

**Comment by pingswept** [comment]
This sounds like a bug. Can anyone replicate this on HEAD in 2017 or later?

**Comment by geowiwi** [comment]
This is still valid and reproducable.

The reason indeed seems to lie within get_topocentric_azimuth_angle(). If you add the correct brackets as @alexfritz indicated, the results are at least in line with what Masters states in chapter 7.4, page 395.

```
def get_topocentric_azimuth_angle(topocentric_local_hour_angle, latitude, topocentric_sun_declination):
-    """Measured eastward from north"""
+    """west is negative, east is positive, Masters p. 395"""
     tlha_rad = math.radians(topocentric_local_hour_angle)
     latitude_rad = math.radians(latitude)
     tsd_rad = math.radians(topocentric_sun_declination)
     a = math.sin(tlha_rad)
     b = math.cos(tlha_rad) * math.sin(latitude_rad) - math.tan(tsd_rad) * math.cos(latitude_rad)
-    return 180.0 + math.degrees(math.atan2(a, b)) % 360
+    return (180 + math.degrees(math.atan2(a, b))) % 360
```

What is the reference for the equation used here?

**Comment by ghulands** [comment]
I've created a PR with updated tests here https://github.com/pingswept/pysolar/pull/54

**Comment by pingswept** [comment]
PR #54 accepted. Thanks @ghulands!
