### ISSUE TITLE
Bug in Altitude calculation

### ISSUE THREAD

**Issue by mrnaz** [pingswept/pysolar#25]
I have been calculating altitude using getAltitude() for every second in a given day, and I've found that some values for utc_datetime result in weird altitude values.

To illustrate the problem, I've created a simple loop that calculates the altitude for each second in a 10 second range.

utc = pytz.timezone('UTC')
tz = pytz.timezone('Australia/Melbourne')
for i in range(0,10,1):
    current = tz.localize(datetime.datetime(2015,5,25,17,36,33))
    current = current + datetime.timedelta(seconds=i)
    u = current.astimezone(utc)
    altitude   = solar.GetAltitude(lat, long, u)
    print(i, current, altitude)

This should result in 10 relatively similar altitude values, right? Here's the actual output:

0 2015-05-25 17:36:33+10:00 -4.590505104749698
1 2015-05-25 17:36:34+10:00 -5.139745001829341
2 2015-05-25 17:36:35+10:00 -5.137986069227229
3 2015-05-25 17:36:36+10:00 -5.113356781660575
4 2015-05-25 17:36:37+10:00 -5.128153217044195
5 2015-05-25 17:36:38+10:00 414.8938077719494
6 2015-05-25 17:36:39+10:00 -5.116501039352879
7 2015-05-25 17:36:40+10:00 -5.085170911710851
8 2015-05-25 17:36:41+10:00 -5.085028778777904
9 2015-05-25 17:36:42+10:00 -5.147078347088631

Note the altitude value for 5. This does not occur when I use the getAltitudefast() function.

**Comment by pingswept** [comment]
That definitely seems screwy. It's particularly weird because this kind of error doesn't appear in the test data (which is admittedly rather sparse, but I think the max altitude error relative to the USNO is around 1 degree, or maybe smaller).

To investigate the problem a little more, could you run the loop across lots of points (maybe a year of seconds?) and then create a histogram of the differences between adjacent points. I think this will tell us whether the error is widespread or rare.

Suggestion: use iPython Notebook and matplotlib for the histogram.

**Comment by mrnaz** [comment]
I also note that when I use minute multiples only (i.e., timedelta(minutes=i) and seconds are always zero) I never seem to get that behaviour. I've not done extensive testing, but I generated a year's worth of altitudes with 1 minute intervals, and charting it in excel didn't immediately reveal any weirdness. I'm still investigating to try to replicate it under different circumstances.

**Comment by mrnaz** [comment]
OK so I've hacked up this to identify how many suspect values are returned for the year 2015 and the code is running now, it'll take around 4 hours on my old machine. I'm not writing every result to the CSV, only every hour's result as well as suspect results, as the 30m+ line CSV is unweildy to evaluate. If this file does not yield insughts into the bug, then I'll hack up some code to input the values into PostgreSQL and we can take it from there.
```
#Data for Melbourne
lat     = -37.755181
long    = 144.9752
tz = pytz.timezone('Australia/Melbourne')
utc = pytz.timezone('UTC')

#Set loop starting parameters
start = tz.localize(datetime.datetime(2015,1,1,0,0,0))
current = start
i = 0
last = 0
f = open('altitude_debugging.csv', 'w')
f.write('Second,Local Date/Time,Altitude,Delta,Flag')
while current.year == start.year:
    # Increment the datetime
    current = start + datetime.timedelta(seconds=i)
    # Create UTC datetime
    u = current.astimezone(utc)
    # Calculate the titude
    altitude = solar.GetAltitude(lat, long, u)
    delta = altitude - last
    if delta < 1 and delta > -1:
        flag = ''
    else:
        flag = 'Suspect'
    last = altitude
    # Output periodically
    if current.minute == 0 and current.second == 0:
        prog = str("{:3.2f}".format(100 * (i/3600) / 8760))+'%'
        print ('%s,%s,%s,%s,%s,%s' % (str(i).zfill(9), prog , current, altitude, delta, flag))
    if (delta < 1 and delta > -1) == False and i > 0:
        prog = str("{:3.2f}".format(100 * (i/3600) / 8760))+'%'
        print ('%s,%s,%s,%s,%s,%s' % (str(i).zfill(9), prog , current, altitude, delta, flag))
        # Write the suspect values for that second to CSV file
        f.write('%s,%s,%s,%s,%s' % (i, current, altitude, delta, flag))
    i += 1
f.close()
```
I've started this code running and I'll paste a summary here when it's done. Do you have any feedback on this process? Is there anything else you can suggest that would be helpful?

**Comment by pingswept** [comment]
That's weird:

    when I use minute multiples only (i.e., timedelta(minutes=i) and seconds are always zero) I never seem to get that behaviour

It explains why I haven't seen the problem before, but I still have no idea why it's happening. My hunch is that something is screwy in the Julian date calculation when seconds are involved.

**Comment by pingswept** [comment]
One other thought: it would be interesting to see what the output of get_julian_solar_day() returns as you sweep through the seconds: https://github.com/pingswept/pysolar/blob/master/pysolar/time.py#L729

**Comment by mrnaz** [comment]
I'll update my script to output the JSD as and run it again overnight for a one year data set. It'll be a multi-GB file, but I'll also write a short script to iterate over it and summarise the suspect data.

However, I don't think it'll turn out to be an incorrect date calculation, and the reason I think this is because the altitude for my first weird value was not in the -180 > x > 180 range.

E.g., In the first post here the weird value given for 2015-05-25 17:36:38+10:00 in the "Australia/Melbourne" timezone was 414.89, and no value for JSD would yield that value, at least to my understanding which I admit is still pretty rudimentary.

**Comment by mrnaz** [comment]
Gah. So I was working from 0.6 rather than -head. My bad.
I am unable to replicate this problem with -head. I have carried out the same steps that I used to invoke the error with the 0.6 codebase (looping over every second in 2015) and, after over 5 million calculations, there are no suspect deltas appearing. I think we can safely close this issue and mark it "n00b reporter".

**Comment by pingswept** [comment]
No worries. I'm glad to hear that the code has been further validated!
