### ISSUE TITLE
Dead code in Julian calendar calculation?

### ISSUE THREAD

**Issue by mrnaz** [pingswept/pysolar#26]
This code is broken, when I attempt to use the function I get the error:
TypeError: unsupported operand type(s) for +: 'datetime.datetime' and 'float'
It probably needs to use the datetime.timedelta() object. I can do this, but I'm still unsure of myself so I'm submitting it as an issue for my coding betters to assess.

It is also wrong. Delta-T cannot be treated as a constant, as far as I know it is an observation-only data point and the code should pull Delta-T (as well as leap second logs, but I think that is included in the datetime lib) from almanacs.

However, this function does not appear to be used anywhere. Unless I call it specifically, it does not seem to get called anywhere.

``` python
def GetJulianEphemerisDay(julian_day, delta_seconds = 66.0):
    """delta_seconds is the value referred to by astronomers as Delta-T, defined as the difference between
    Dynamical Time (TD) and Universal Time (UT). In 2007, it's around 65 seconds.
    A list of values for Delta-T can be found here: ftp://maia.usno.navy.mil/ser7/deltat.data

    More details: http://en.wikipedia.org/wiki/DeltaT

    """
    return julian_day + (delta_seconds / 86400.0)
```

**Comment by pingswept** [comment]
Ah, I think you have discovered the vestiges of a previous Julian calendar implementation. You might double check to be sure, but I think that function was superseded by the leap second calculation that Lawrence d'Oliveiro implemented in this rather massive patch: https://github.com/pingswept/pysolar/commit/e2dce16af47c2e2dcac91b9ea2c0013d0a90abf0#diff-fdfb52188cf56f1f08086d75bffc5eb0

(By the way, I'm assuming you're working off of the latest code on Github, yes?)

**Comment by mrnaz** [comment]
I was running off 0.6, which I'd downloaded a few months ago and assumed 
it was latest. I've just downloaded the latest version and updated my 
code (eg solar.GetAltitude() has changed to solar.get_altitude() etc) 
and I'm running my test loops again.

I think I'll get in touch with Lawrence just to say that, as a user, I 
appreciate his contribution. The least one can do to repay those from 
whom one derives benefit is to thank them.
I'll be in touch with the output of my test suite in HEAD, and I'm 
feeling a bit sheepish for not checking that I was working from the 
latest codebase ages ago.

- Naz.

**Comment by pingswept** [comment]
I think this is actual dead code. Patches for removal welcome, if you can verify it's dead.
