### ISSUE TITLE
error in get_azimuth_fast, timestamp() missing

### ISSUE THREAD

**Issue by biglimp** [pingswept/pysolar#28]
I cannot get the azimuth function to work. Maybe I am doing something wrong but I spend a lot of time trying to get this correct. The altitude angle is calculated but wrong. What am I doing wrong, or is thi a bug? Please help...

Fredrik

C:\Python27\python.exe -u C:\Program Files (x86)\JetBrains\PyCharm 3.4.1\helpers\pydev\pydevconsole.py 13590 13591
PyDev console: starting.import sys; print('Python %s on %s' % (sys.version, sys.platform))
Python 2.7.8 (default, Jun 30 2014, 16:03:49) [MSC v.1500 32 bit (Intel)] on win32
sys.path.extend(['M:\\PythonScripts\\dataprocessing_Python'])

from pysolar import solar
import datetime

solar.get_altitude_fast(57.7,12.0,datetime.datetime.now())
34.339120191173976

solar.get_azimuth_fast(57.7,12.0,datetime.datetime.now())

Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "M:\PythonScripts\dataprocessing_Python\pysolar\solar.py", line 135, in get_azimuth_fast
    altitude_rad = math.radians(get_altitude(latitude_deg, longitude_deg, when))
  File "M:\PythonScripts\dataprocessing_Python\pysolar\solar.py", line 58, in get_altitude
    jd = time.get_julian_solar_day(when)
  File "M:\PythonScripts\dataprocessing_Python\pysolar\time.py", line 742, in get_julian_solar_day
    +
AttributeError: 'datetime.datetime' object has no attribute 'timestamp'

**Comment by pingswept** [comment]
If you find yourself getting errors like AttributeError: ‘datetime.datetime’ object has no attribute ‘timestamp’, this probably means that you are using Python 2 instead of Python 3.

Pysolar no longer supports Python 2. So far, nobody has volunteered to do the work to backport the code to Python 2. If you’re stuck on Python 2 because of some other dependency, you should use Pysolar 0.6, which is the last version that works with Python 2.

**Comment by di0spyr0s** [comment]
I am using python 3.2.3 and have the same error.

As far as I can tell, 

```python
import datetime
import time

current_time = time.time()
datetime.datetime.timestamp(current_time)

```

will always result in an attribute error as the datetime module doesn't use 'timestamp' it uses 'fromtimestamp'

```python
import time
import datetime

current_time = time.time()
datetime.datetime.fromtimestamp()
```

will work just fine, however, your examples here: http://docs.pysolar.org/en/latest/

show a datetime object being passed to these functions, not a timestamp. 

```
>>> from pysolar.solar import *
>>> import datetime
>>> d = datetime.datetime.now()
>>> get_altitude(42.206, -71.382, d)
24.39867440096082
>>> d = datetime.datetime(2007, 2, 18, 15, 13, 1, 130320)
>>> get_altitude(42.206, -71.382, d)
20.374937135509537
```

So the code will break anyway, as datetime.datetime.fromtimestamp() will not work if passed a datetime object.

**Comment by pingswept** [comment]
Ah, sorry about that. I think the patch you sent fixes this. Thanks!
