### ISSUE TITLE
strange values for pysolar.util.extraterrestrial_irrad()

### ISSUE THREAD

**Issue by rbuffat** [pingswept/pysolar#33]
In the function description it is stated "On average the extraterrestrial irradiance
    is 1367 Watts/meter2 (W/m2). This value varies by + or - 3 percent as the earth orbits the sun."

I get a value of  around -211.

ZA = math.sin(latitude_deg) \* math.sin(decl) + math.cos(latitude_deg) \* math.cos(decl) \* math.cos(ha)

latitude_deg, decl as well ha are in degrees while math.sin / math.cos expect radians.

**Comment by pingswept** [comment]
Yeah, that looks totally wrong. Patches that made the calculation work properly are very welcome.

**Comment by rbuffat** [comment]
I did not find the reference

[2] Dr. J. Schumacher and et al,"INSEL LE(Integrated Simulation Environment Language)Block reference",p.68

If somebody is able to point me to the reference I could look into it.

**Comment by dacoex** [comment]
@rbuffat 

>If somebody is able to point me to the reference I could look into it.

http://www.insel.eu/index.php?id=20&L=1
http://www.insel.eu/fileadmin/insel.eu/diverseDokumente/blockReference/inselBlockReference_en.pdf

**Comment by pingswept** [comment]
I believe this was an actual bug that was fixed recently: https://github.com/pingswept/pysolar/commit/c4305de0476765ca883013eff3d33b6e06f0387f
