### ISSUE TITLE
Reference picture: Azimuth wrong way?

### ISSUE THREAD

**Issue by s9w** [pingswept/pysolar#37]
Hey. I'm an amateur in these things, but isn't the reference graphic exactly wrong in terms of azimuth? The text says zero is south, and positive values go from there to the east. Yet the arc goes from south to the west towards the example position, which would mean an azimuth of maybe 70°. When in fact the "right" way would be all the way around and more like 290°.

**Comment by pingswept** [comment]
Assuming you're referring to this picture: http://docs.pysolar.org/en/latest/_images/reference_frame.png

The arc shown is an azimuth of around -70°. This is different from how other programs or conventions reckon azimuth, but it is the convention used by the NREL solar position algorithm that Pysolar implements. Make sense?

**Comment by s9w** [comment]
I'm confused by the use of negative angles. I would agree it's -70, but would have called it 290. But I'm not familiar with the conventions and it seems to be custom to use negative angles, so it's probably right then. My problem was that I would have expected to only use positive angles, and therefore the "long" way around.

**Comment by pingswept** [comment]
Fair enough. You could stick with all positive angles and get through life just fine. Cheers.
