### ISSUE TITLE
UTC time zones

### ISSUE THREAD

**Issue by LorenzoBottaccioli** [pingswept/pysolar#40]
Hello,

Is it required to set the UTC time zone in order to use `get_azimuth` or `get_altitude` as is required by the Sun Position Algorithm in Matlab? Because I get different results from the two algorithms and the difference is related to the UTC. If is need to set the UTC where do i set it? I'm using a code like this in Pysolar 0.6:

```
import pandas as pd
import Pysolar.solar as pys

df = pd.read_csv('radiation.csv', sep=";", index_col='Date Time', decimal=',')
df.index = pd.to_datetime(df.index, unit='s')

azimuth=pys.GetAzimuth(latitude, longitude, df.index[i], elevation)
zenith = 90-pys.GetAltitude(latitude, longitude, df.index[i], elevation)
```

In the Matlab version of the algorithm the funztion sun_position takes as input 2 structs one containing location info (lat, lon, elev) and a time struct that contains (Year, Month, Day, Hour, Minute, Second and UTC time).

Thanks

**Comment by pingswept** [comment]
Sorry, not a code issue. Good luck!
