### ISSUE TITLE
Deploy pysolar v0.6.0 on pypi for easy support of latest python 2.x

### ISSUE THREAD

**Issue by jf-mgd** [pingswept/pysolar#41]
PIP is now installed with python 2.x, so a 0.6.0 package of this lib makes sense.

**Comment by pingswept** [comment]
That's a reasonable suggestion, but I don't know of any Pysolar users who don't use Python 3 who will do the work to get the package on PyPI. It's probably easy to do, but I haven't looked into the details. Any volunteers to do the work, please email me.

**Comment by pingswept** [comment]
Volunteers to do this still welcome!

**Comment by pingswept** [comment]
This is probably already possible. 0.6 is available on PyPI, and you can install it using: `pip install pysolar==0.6`

Closing for now, unless someone runs into trouble with this.
