### ISSUE TITLE
I would like to make a pull request but not to the master.

### ISSUE THREAD

**Issue by DouglasAllen** [pingswept/pysolar#45]
Could you open a dev branch and then I'll make the pull request to that if you will.
I have many changes that should not just be blindly merged. Mine is still in dev so is not yet
complete. My refactoring left two test failing and I may need help to fix them. Thanks.
I'm finding ways to make this package more accurate. Since I got into this one of my starting points
was this site and I just read the source code. [LONG-TERM ALMANAC FOR SUN, MOON, AND POLARIS  V1.11 ](http://www.celnav.de/longterm.htm)
Then this one sort of reminds me of that but I can't see any source code and it leaves a few things to be desired. [MIDC SPA Calculator](https://www.nrel.gov/midc/solpos/spa.html)
One of the things that bugged me enough to even work on this was the pylint extension for VS-Code editor from Microsoft. Yes I'm on Windows.

**Comment by pingswept** [comment]
Hi DouglasAllen,

Just made a dev branch for you.

One request: please separate whatever pulls you'd like to request into small, discrete changes. I take the validation of changes pretty seriously, and if you have a huge request with some obvious stuff and some stuff that will take some work for me to validate, then I won't accept it until it's all good, which could take a long time, potentially forever, given that this is just a hobby for me.

**Comment by DouglasAllen** [comment]
K. Thanks for your reply. I need to mention something about the package that is out there from a pip install. I installed it that way and then ran the tests from your master branch but here's the error.
======================================================================
ERROR: test_timestamp (__main__.testSolar)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\Users\kb9agt\github\python_lang\pysolar\test\testsolar.py", line 77, in test_timestamp
    print('d', time.timestamp(self.d))
AttributeError: module 'pysolar.time' has no attribute 'timestamp'

**Comment by DouglasAllen** [comment]
Next is a lot of issues with my pylint cop.
That is mostly why I want to help refactor all this.
But first small change is to rename all 'when' to 'now' because when do you want it?
It's two letters shorter and just makes sense to me. 
Like you said I won't do a whole lot at once but that is a lot of editing.
Let you tests decide though after I complete that task.
