### ISSUE TITLE
get_azimuth() or get_altitude() values are false

### ISSUE THREAD

**Issue by GarennePb** [pingswept/pysolar#53]
Hi ! 
I'm using pysolar with a gps and actual time, I'm trying to make it works but it seems that I have some problems.
**EDIT:** 
How can I handle this warning without considering that is it an error and do a `try: except:`? : 
```
/usr/local/lib/python3.4/dist-packages/pysolar/time.py:105: UserWarning: I don't know about leap seconds after 2015
  (leap_seconds_base_year + len(leap_seconds_adjustments) - 1)
```
Any ideas ? Thanks in advance !

**Comment by pingswept** [comment]
Fixed, at least until 2018, in pull request #60.
