### ISSUE TITLE
Update leap seconds

### ISSUE THREAD

**Issue by ghulands** [pingswept/pysolar#56]
UserWarning: I don't know about leap seconds after 2015

Need to update leap_seconds_adjustments and delta_t.

leap_seconds_adjustments only goes to 2015 and delta_t only goes to April 2014.

**Comment by pingswept** [comment]
Pull request welcome. I suspect new leap second data has been published by some authoritative folks on the internet.

**Comment by ArneBachmann** [comment]
Isn't it part of some database or other library already? What about the `pytz` package?
Adding further dependencies, of course, is not very welcome.

**Comment by ArneBachmann** [comment]
This has some recent data:
https://www.nist.gov/pml/time-and-frequency-division/atomic-standards/leap-second-and-ut1-utc-information

**Comment by ArneBachmann** [comment]
Solved in #60.
