### ISSUE TITLE
datetime in UTC

### ISSUE THREAD

**Issue by mikewen** [pingswept/pysolar#58]
What is wrong use UTC ?

Could you explain why it is naive to use datetime in UTC?

I always use UTC (or unix epoch timestamp) for my server Apps because of  so many different time zones and daylight savings.

Thanks!
Mike,

**Comment by ArneBachmann** [comment]
I think one problem with Python's `datetime.datetime` is, that by default it uses the system's timezone settings and copies it into the datetime object if `tzinfo` parameter is left at `None`. It is, however, a naive timestamp in the sense that it is not aware of the timezone, but only retains the timezone offset, thus not allowing to change the date into or out of DST dates with change of the timezone offset. If will simply stick as provided.
At least, that's how far I understood it at the moment.

**Comment by pingswept** [comment]
@mikewen I think there's a misunderstanding of the use of the word "naive" here. A naive datetime just refers to a datetime object that does not specify a time zone offset relative to UTC. I think it's very reasonable to perform all your calculations in UTC.
