### ISSUE TITLE
Create package stub for typeshed

### ISSUE THREAD

**Issue by ArneBachmann** [pingswept/pysolar#62]
https://github.com/python/typeshed/
You create `*.pyi` interface stubs that tell Python type checkers (like mypy) what interfaces to expect.
This allows all code that uses pysolar to be type checked even for library calls into pysolar.

**Comment by pingswept** [comment]
This would be a welcome addition if someone wants to write the `*.pyi` file.

**Comment by ArneBachmann** [comment]
I´m working on it

**Comment by ArneBachmann** [comment]
Almost done

**Comment by pingswept** [comment]
Taken care of in PR #79.
