### ISSUE TITLE
Leap second issue!

### ISSUE THREAD

**Issue by Setureh** [pingswept/pysolar#66]
Hi,

I just updated pysolar --conda -- (so not an old one) and I get the error:
pysolar/time.py:105: UserWarning: I don't know about leap seconds after 2015
 (leap_seconds_base_year + len(leap_seconds_adjustments) - 1)

I am looking for some data for 2016 and 2017.
I read the other posts about the issue but I did not get how to solve the problem.
( I am not a professional coder)

Can you explain me in some simple way how to solve this problem?

**Comment by pingswept** [comment]
The leap second data has been updated through 2017 in the master branch of the code. You could either figure out how to update your code to that version, or you could alter your copy of the file time.py manually, or you could just ignore the warning, given how little the sun moves in a second.
