### ISSUE TITLE
Sun position at high elevations

### ISSUE THREAD

**Issue by jonas-hagen** [pingswept/pysolar#67]
(I am using the master branch version.)

I am trying to get sunrise and sunset times in high elevations (up to 100 km above sea level). As the `get_{altitude|position}()` functions take an elevation argument, I would expect them to return a different value for sun altitude, based on the given elevation.

``` python console
>>> import datetime
>>> from pysolar import solar
>>> sunrise_time = datetime.datetime(2018,3,12,6,55,0)
>>> solar.get_position(46.95, 7.47, sunrise_time, elevation=100000)
(95.03439124507312, 0.5961510806209467)
>>> solar.get_position(46.95, 7.47, sunrise_time, elevation=0)
(95.03439124029069, 0.596183960394498)
```
The difference between the two altitudes is in the order of 3e-5 and thus much less than expected. What is the elevation parameter and how could I get the sun altitude in arbitrary elevations?

**Comment by pingswept** [comment]
Answered (sort of) on mailing list: http://lists.pysolar.org/2018-03/0000001.html
