### ISSUE TITLE
Inverted documentation for azimuth.

### ISSUE THREAD

**Issue by lvella** [pingswept/pysolar#81]
Besides issue #75, [azimuth's documentation](http://docs.pysolar.org/en/latest/#examples) seems at odds with the program: it says south is zero, but retrieving the azimuth for noon at a southern hemisphere point with `solar.get_azimuth(-18.9132481, -48.2584742, noon)`, will give me a value around zero, but it is expected a value around 180, since sun's arc is around north for southern hemisphere.

What is the correct interpretation of the value returned by `solar.get_azimuth()`?

**Comment by lvella** [comment]
I did a comparison with PyEphem, and `solar.get_azimuth()` uses the same reference system they, i.e., azimuth measured at east of north (which makes the documentation wrong?).

Maybe someone changed the reference direction, but forgot to update the documentation and `solar.get_azimuth_fast()`, leading to this and issue #75 ?

**Comment by AmitAronovitch** [comment]
Seems like the azimuths on master correspond to the standard definition (clockwise from north, as in other ephemeris libraries), whereas the azimuths on the latest version available on pypi are different (probably match the definition that is in the docs).
Supposing we fix the docs, is there anything else blocking release of next version to pypi (I need the standard azimuths, so right now cannot use the latest release...)
