### ISSUE TITLE
Update pysolar version on PyPI?

### ISSUE THREAD

**Issue by adbuerger** [pingswept/pysolar#85]
The version of pysolar hosted on PyPI labeled 0.7 is from April 2015. Do you consider releasing a newer version 0.8 (or similar) there to also make recent developments and fixes in pysolar available for installation via pip?

**Comment by pingswept** [comment]
I'm going to tag 0.8RC2 right now and see if anyone complains in the next few days. If nobody does, I'll call that 0.8 and push it to PyPI.

**Comment by pingswept** [comment]
Okay, 0.8 is up on PyPI.

Let testing roll down like waters and bug reports like a mighty stream.
