### ISSUE TITLE
docs.pysolar.org not updating automatically?

### ISSUE THREAD

**Issue by pingswept** [pingswept/pysolar#88]
It looks like ReadTheDocs has changed the way they talk to Github, so the docs at docs.pysolar.org aren't getting updated automatically any more.

Note that
http://docs.pysolar.org/en/latest/_images/reference_frame.png
is not the same as 
https://github.com/pingswept/pysolar/blob/master/doc/img/reference_frame.png
but they should be identical.

**Comment by paulocheque** [comment]
To help on this it would require some read the docs and github permissions.. but checking some links, maybe this can help: https://docs.readthedocs.io/en/latest/versions.html#how-we-envision-versions-working

**Comment by pingswept** [comment]
I think I just fixed this. Github had deprecated their old service integration model and moved to "webhooks." The documentation should be rebuilt automatically now on every commit. (I also manually rebuilt the docs, so they are at least up-to-date for release 0.8.)
