### ISSUE TITLE
How to involve surface declination and tilt angle?

### ISSUE THREAD

**Issue by mirtaheri** [pingswept/pysolar#89]
Hello,

I wonder how one can take into account a surface declination either for Altitude and Direct Radiation,
which function may I touch to insert in a correct way either a PV tilt and azimuth w.r.t the references?

As the following code considers a plane tangent to the simulation point on the ground:

`import pysolar` 
`import numpy as np` 
`from datetime import *` 
`import pytz as tz`

`dt_start = datetime(2018,6,18, 0, 0, 0, tzinfo=tz.utc)`
`dt_end =   datetime(2018,6,19, 0, 0, 0, tzinfo=tz.utc)`
`lat, long, elevation = 45, 11, 100`
`step = 60`
`tilt = 10; declination = 10 ` #degrees

`alt_func = lambda t: pysolar.solar.get_altitude(lat, long, t)`

`alt_func_vect = np.vectorize(alt_func)`

`sim_time_array = np.arange(dt_start, dt_end, timedelta(seconds = step)).astype(datetime)`

`altitues = alt_func_vect(sim_time_array)`

`rad_func = lambda date, altitude_deg: pysolar.radiation.get_radiation_direct(date, altitude_deg)`

`rad_func_vect = np.vectorize(rad_func)`

`radiations = rad_func_vect(sim_time_array, altitues)`

`radiations[altitues<=0] = 0`
 
![picture1](https://user-images.githubusercontent.com/9678587/46088014-c8f70380-c1ab-11e8-8afe-1aa419f127b8.png)

So I would like to know first this is already considered in kind of function arguments and if not, which one can I modify to add this functionality.

Thanks in advance.

**Comment by pingswept** [comment]
The surface declination is not considered in calculating the location of the sun; you should calculate the location of the sun relative to a horizontal plane tangent to the earth, and then adjust that value by your declination.

But in any case, this is not an issue with the software, so I'm closing this issue. Good luck!
