### ISSUE TITLE
get_azimuth and get_azimuth_fast

### ISSUE THREAD

**Issue by paulocheque** [pingswept/pysolar#90]
Hey, I didn't find any doc relative to the differences of these two methods. Any tips?

Also, running `get_azimuth` for the entire day I didn't get any negative values. Is the doc out of date?

Thanks in advance and congratulations for the cool library!

**Comment by AmitAronovitch** [comment]
I am assuming you are using the latest version (0.8).

Yes, unfortunately ReadTheDocs integration had stopped working (issue https://github.com/pingswept/pysolar/issues/88 - help would be appreciated), so it shows the documentation of an older version (and the definition of the azimuth had changed between these versions).

Meanwhile you can view the up-to-date docs directly from github: https://github.com/pingswept/pysolar/blob/master/doc/index.rst

1. The difference between the functions is that `get_azimuth_fast` uses a simplified formula, so it is faster but less accurate (this is mentioned in the docstring - perhaps we should add an API reference, so it will appear in the static documentation as well).

2. No negative values: that is correct. In current version, azimuth range is from 0 to 360. For locations in the northern hemisphere, daytime sun azimuth should be between 90 to 270.

**Comment by pingswept** [comment]
Just fixed issue #88, so this should be fixed too. Feel free to re-open if I'm wrong.
