### ISSUE TITLE
Question: get_radiation_direct()

### ISSUE THREAD

**Issue by paulocheque** [pingswept/pysolar#92]
`... get_radiation_direct() returns a value in watts per square meter ...`

What is the period of time that represents the result of this function? An entire day? I mean, I get a value 909 like in the example, so I can interpret:

`the average insolation for that lat/long point is 909 W/m2 in the 5th day of the year 2018`

Is that correct?

And what about the 0.8 version? Should it return 0s at night?

I am asking because of this comment: `As of version 0.7, the function is not smart enough to return zeros at night`

**Comment by paulocheque** [comment]
The other thing, I saw this function doesn't use the `azimuth`, only the `altitude`. Is that expected? That is because the value is an average of the entire day?

**Comment by jeromelebel** [comment]
I guess your square meter on the ground receive sun according to the altitude of the sun only. The square meter on the ground doesn't care if the sun arrives from the east, the south, or the west.
