### ISSUE TITLE
Supported Python versions

### ISSUE THREAD

**Issue by codingjoe** [pingswept/pysolar#97]
Hi there!

I think the documentation is a little bit outdated. The latest version 0.8.0 does only support Python 3.6+.
The documentation points to 3.4 and talks about not supporting python 2.

This was the commit breaking <3.6 support: https://github.com/pingswept/pysolar/commit/6c52c700a745838f8baa1188bc8a5dd7f850a682#r31253580

I don't really mind about supporting anything but Python 3.7, but I guess the documentation could be improved.

Best
-Joe

**Comment by pingswept** [comment]
Good point. Patches welcome.

**Comment by pingswept** [comment]
Either path is acceptable to me. If there is an easy workaround to the absence of the ModuleNotFound exception, I'd slightly prefer to support a broader range of Python versions, but if not, just changing the docs to 3.6+ is fine.
